/**
 * ExportButton
 * Exports the analysis as JSON or Markdown
 */

"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, FileJson, FileText, ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";
import type { FullProfileAnalysis } from "@/lib/types/profile";

interface Props {
  analysis: FullProfileAnalysis;
}

function toMarkdown(a: FullProfileAnalysis): string {
  const grade = a.letterGrade;
  const cats = Object.values(a.categories);

  const categorySection = cats.map(cat => {
    const recs = cat.recommendations.map(r => `  - ${r}`).join("\n");
    return `### ${cat.label} — ${cat.score}/100\n${recs}`;
  }).join("\n\n");

  const roadmapSection = a.roadmap.map((r, i) =>
    `| ${i + 1} | ${r.action.slice(0, 80)}${r.action.length > 80 ? "…" : ""} | ${r.priority} | ${r.effort} | ${r.impact} | ${r.timeframe} |`
  ).join("\n");

  const rolesSection = a.suggestedRoles.map(r =>
    `- **${r.title}** — ${r.match}% match | Salary: ${r.salary ?? "N/A"}`
  ).join("\n");

  return `# GitHub Profile Analysis: @${a.username}

**Overall Score:** ${a.overallScore}/100 (${grade})
**Benchmark:** ${a.benchmark.label}
**Generated:** ${new Date(a.generatedAt).toLocaleDateString()}

---

## Profile Stats

- Followers: ${a.profile.followers} | Following: ${a.profile.following}
- Public Repos: ${a.profile.public_repos} | Gists: ${a.profile.public_gists}
- Total Stars: ${a.totalStars} | Total Forks: ${a.totalForks}
- Account Age: ${Math.floor(a.accountAge / 365)}y ${Math.floor((a.accountAge % 365) / 30)}m
- Primary Languages: ${a.primaryLanguages.join(", ")}

---

## Category Scores

${categorySection}

---

## Suggested Job Roles

${rolesSection}

---

## Improvement Roadmap

| # | Action | Priority | Effort | Impact | Timeframe |
|---|--------|----------|--------|--------|-----------|
${roadmapSection}

---

*Report generated by [RepoLens](https://github.com) Profile Analysis*
`;
}

export function ExportButton({ analysis }: Props) {
  const [open, setOpen] = useState(false);

  const exportJson = () => {
    const blob = new Blob([JSON.stringify(analysis, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${analysis.username}-profile-analysis.json`;
    a.click(); URL.revokeObjectURL(url);
    setOpen(false);
  };

  const exportMarkdown = () => {
    const blob = new Blob([toMarkdown(analysis)], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = `${analysis.username}-profile-analysis.md`;
    a.click(); URL.revokeObjectURL(url);
    setOpen(false);
  };

  return (
    <div className="relative">
      <Button
        variant="outline"
        size="sm"
        onClick={() => setOpen(v => !v)}
        className="border-white/[0.08] hover:bg-white/[0.05] text-slate-300"
      >
        <Download className="w-4 h-4 mr-2" />
        Export
        <ChevronDown className={cn("w-3 h-3 ml-1.5 transition-transform", open && "rotate-180")} />
      </Button>

      {open && (
        <>
          <div className="fixed inset-0 z-10" onClick={() => setOpen(false)} />
          <div className="absolute right-0 mt-1 z-20 glass-card rounded-lg border border-white/[0.08] py-1 min-w-[160px] shadow-xl">
            <button
              onClick={exportJson}
              className="flex items-center gap-2.5 w-full px-4 py-2 text-sm text-slate-300 hover:bg-white/[0.05] hover:text-white transition-colors"
            >
              <FileJson className="w-4 h-4 text-[#00e5ff]" />
              Export JSON
            </button>
            <button
              onClick={exportMarkdown}
              className="flex items-center gap-2.5 w-full px-4 py-2 text-sm text-slate-300 hover:bg-white/[0.05] hover:text-white transition-colors"
            >
              <FileText className="w-4 h-4 text-[#7c3aed]" />
              Export Markdown
            </button>
          </div>
        </>
      )}
    </div>
  );
}
